### ISSUE TITLE
curlToHAR not recognized

### ISSUE THREAD

**Issue by ShwethaSwaminathan** [Leventhan/curl-to-har#1]
Hi,

I'm using the sample uses code.
When I try to run the code it gives me this error: 
/home/root/access.js:7
var HAR = curlToHAR(str);
          ^
ReferenceError: curlToHAR is not defined
    at Object.<anonymous> (/home/root/access.js:7:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

Let me know if there's something I'm missing.

**Comment by yosriady** [comment]
Sorry, the sample code should be `curlToHar`. I've updated the README. Thanks for reporting this issue!
